Import helpers from babel-types
[[[Prompt]]]

Your plugin resulted in an error:

```
$ yarn build
ReferenceError: /home/qnighy/workdir/babel-plugin-const-to-function/src/index.js: t is not defined
    at /home/qnighy/workdir/babel-plugin-const-to-function/babel.config.js:10:26
    at Array.forEach (<anonymous>)
    at PluginPass.VariableDeclaration (/home/qnighy/workdir/babel-plugin-const-to-function/babel.config.js:7:32)
    at newFn (/home/qnighy/workdir/babel-plugin-const-to-function/.yarn/cache/@babel-traverse-npm-7.20.5-dc0e9498d7-c7fed46861.zip/node_modules/@babel/traverse/lib/visitors.js:159:21)
    at NodePath._call (/home/qnighy/workdir/babel-plugin-const-to-function/.yarn/cache/@babel-traverse-npm-7.20.5-dc0e9498d7-c7fed46861.zip/node_modules/@babel/traverse/lib/path/context.js:46:20)
    at NodePath.call (/home/qnighy/workdir/babel-plugin-const-to-function/.yarn/cache/@babel-traverse-npm-7.20.5-dc0e9498d7-c7fed46861.zip/node_modules/@babel/traverse/lib/path/context.js:36:17)
    at NodePath.visit (/home/qnighy/workdir/babel-plugin-const-to-function/.yarn/cache/@babel-traverse-npm-7.20.5-dc0e9498d7-c7fed46861.zip/node_modules/@babel/traverse/lib/path/context.js:84:31)
    at TraversalContext.visitQueue (/home/qnighy/workdir/babel-plugin-const-to-function/.yarn/cache/@babel-traverse-npm-7.20.5-dc0e9498d7-c7fed46861.zip/node_modules/@babel/traverse/lib/context.js:96:16)
    at TraversalContext.visitMultiple (/home/qnighy/workdir/babel-plugin-const-to-function/.yarn/cache/@babel-traverse-npm-7.20.5-dc0e9498d7-c7fed46861.zip/node_modules/@babel/traverse/lib/context.js:67:17)
    at TraversalContext.visit (/home/qnighy/workdir/babel-plugin-const-to-function/.yarn/cache/@babel-traverse-npm-7.20.5-dc0e9498d7-c7fed46861.zip/node_modules/@babel/traverse/lib/context.js:119:19) {
  code: 'BABEL_TRANSFORM_ERROR'
}
```

[[[Answer]]]

In the code example I provided, t is a reference to the babel-types module, which provides utilities for creating AST nodes. In order for the code to run correctly, you will need to import the babel-types module at the top of the file and destructure the functionDeclaration method from it. Here is an updated version of the code that should fix the error:

```
const { functionDeclaration } = require("babel-types");

const myBabelPlugin = {
  visitor: {
    // This visitor will be applied to all `VariableDeclaration` nodes with `const` or `let` declarations
    VariableDeclaration(path) {
      if (path.node.kind === "const" || path.node.kind === "let") {
        // For each `VariableDeclarator` node in the declaration, we check if it's an arrow function
        path.node.declarations.forEach((declarator) => {
          if (declarator.init && declarator.init.type === "ArrowFunctionExpression") {
            // If it is, we create a new `FunctionDeclaration` node with the same name and function body
            const func = functionDeclaration(
              declarator.id,
              declarator.init.params,
              declarator.init.body,
              declarator.init.generator,
              declarator.init.async
            );

            // And replace the original `VariableDeclarator` node with the new `FunctionDeclaration` node
            path.replaceWith(func);
          }
        });
      }
    }
  }
};
```